/* PEPMOSA storefront repair layer: admin-approved fee -> email verification -> ordering. */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const peso=v=>'₱'+Number(v||0).toLocaleString('en-PH',{minimumFractionDigits:2});
  let gb=null, products=[], minimums=[];
  let feePayment=null, verifiedEmail=localStorage.getItem('pepmosa_verified_email')||'', lastFeeStatus=null;
  function sb(){return window.sb||window.__sb;}
  function styles(){if($('pepFeeStyles'))return;const s=document.createElement('style');s.id='pepFeeStyles';s.textContent=`
    .pepFeeBtn{border:0;border-radius:12px;padding:12px 18px;font-weight:900;cursor:pointer;background:#d7288d;color:#fff}.pepFeeBtn.secondary{background:#fff;color:#2b222a;border:1px solid #ead7e3}.pepFeeBtn:disabled{opacity:.55;cursor:not-allowed}
    .pepFeeModal{position:fixed;inset:0;background:rgba(27,17,25,.56);display:none;align-items:center;justify-content:center;padding:18px;z-index:99999}.pepFeeModal.open{display:flex}
    .pepFeeBox{width:min(560px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:26px;box-shadow:0 24px 80px rgba(0,0,0,.25)}
    .pepFeeBox h2{margin:0 0 8px}.pepFeeMuted{color:#746a73;font-size:13px;line-height:1.55}.pepFeeField{display:flex;flex-direction:column;gap:6px;margin-top:13px}.pepFeeField label{font-size:11px;font-weight:900;text-transform:uppercase}.pepFeeField input{width:100%;box-sizing:border-box;border:1px solid #e5d4e0;border-radius:12px;padding:12px}
    .pepFeeNotice{padding:13px 15px;border-radius:13px;background:#fff1fa;margin:12px 0}.pepFeeNotice.success{background:#e8f8ef;color:#176e42}.pepFeeNotice.warn{background:#fff7df;color:#805f00}.pepFeeNotice.error{background:#fff0f3;color:#a5253e}.pepFeeActions{display:flex;gap:9px;flex-wrap:wrap;margin-top:17px}
    .pepFeeStatus{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:900}.pepFeeStatus.pending{background:#fff1ce;color:#8b6500}.pepFeeStatus.paid{background:#e6f8ef;color:#177044}.pepFeeStatus.rejected{background:#ffe9ed;color:#b32745}
  `;document.head.appendChild(s)}
  function modal(id,html){if($(id))return;const d=document.createElement('div');d.id=id;d.className='pepFeeModal';d.innerHTML=html;d.onclick=e=>{if(e.target===d)d.classList.remove('open')};document.body.appendChild(d)}
  function ensureUI(){styles();const status=$('gbStatus');if(status&&!$('pepFeeCard')){const c=document.createElement('div');c.id='pepFeeCard';c.className='notice';c.style.marginTop='14px';c.innerHTML='<div style="font-weight:900">GROUP BUY ACCESS</div><div id="pepFeeState" class="pepFeeMuted" style="margin:5px 0 10px">Loading…</div><button id="pepFeeAction" class="pepFeeBtn">PAY ADMIN FEE</button>';status.parentNode.insertBefore(c,status.nextSibling);$('pepFeeAction').onclick=feeAction}
    modal('pepFeeModal',`<div class="pepFeeBox"><h2>Group Buy Access</h2><div id="pepFeeGb" class="pepFeeNotice"></div><div class="pepFeeField"><label>Full Name *</label><input id="pepFeeName" placeholder="Your full name"></div><div class="pepFeeField"><label>Telegram Name *</label><input id="pepFeeTelegram" placeholder="@telegramname"></div><div class="pepFeeField"><label>Mobile Number *</label><input id="pepFeePhone" placeholder="09xxxxxxxxx"></div><div class="pepFeeField"><label>Payment Proof *</label><input id="pepFeeProof" type="file" accept="image/*,.pdf"><div class="pepFeeMuted">Upload your payment receipt/screenshot. Required.</div></div><div id="pepFeeMsg"></div><div class="pepFeeActions"><button id="pepFeeSubmit" class="pepFeeBtn">I HAVE PAID</button><button class="pepFeeBtn secondary" onclick="document.getElementById('pepFeeModal').classList.remove('open')">CANCEL</button></div></div>`);
    modal('pepVerifyModal',`<div class="pepFeeBox"><h2>Verify Your Email</h2><div id="pepVerifyBody" class="pepFeeMuted">Your admin fee has been approved. Verify your email to unlock ordering.</div><div class="pepFeeField"><label>Email *</label><input id="pepVerifyEmail" type="email" placeholder="your@email.com"></div><div id="pepVerifyMsg"></div><div class="pepFeeActions"><button id="pepVerifySend" class="pepFeeBtn">SEND VERIFICATION EMAIL</button><button class="pepFeeBtn secondary" onclick="document.getElementById('pepVerifyModal').classList.remove('open')">CLOSE</button></div></div>`);
    modal('pepInfoModal',`<div class="pepFeeBox" style="text-align:center"><div style="font-size:44px">✓</div><h2 id="pepInfoTitle">Success</h2><div id="pepInfoText" class="pepFeeMuted"></div><div class="pepFeeActions" style="justify-content:center"><button id="pepInfoOk" class="pepFeeBtn">OK</button></div></div>`);$('pepFeeSubmit').onclick=submitFee;$('pepVerifySend').onclick=sendVerify;$('pepInfoOk').onclick=()=> $('pepInfoModal').classList.remove('open')}
  function info(title,text){$('pepInfoTitle').textContent=title;$('pepInfoText').textContent=text;$('pepInfoOk').textContent='OK';$('pepInfoModal').classList.add('open')}
  async function findFee(){if(!gb||!sb())return null;const S=sb(),id=localStorage.getItem('pepmosa_fee_payment_id');if(id){const r=await S.from('admin_fee_payments').select('*').eq('id',id).eq('gb_number',gb.gb_number).maybeSingle();if(!r.error&&r.data)return r.data}const email=(localStorage.getItem('pepmosa_customer_email')||'').trim().toLowerCase();if(!email)return null;const r=await S.from('admin_fee_payments').select('*').eq('gb_number',gb.gb_number).eq('email',email).order('created_at',{ascending:false}).limit(1);return r.error?null:(r.data||[])[0]||null}
  async function refreshFeeState(){const previous=feePayment?.status||lastFeeStatus;feePayment=await findFee();lastFeeStatus=feePayment?.status||null;const state=$('pepFeeState'),btn=$('pepFeeAction');if(!state||!btn)return;if(previous==='SUBMITTED'&&feePayment?.status==='PAID'){info('Admin Fee Approved ✓','Your admin fee payment has been approved. You may now verify your email to continue ordering.');setTimeout(()=>openVerify(),300)}if(!feePayment){state.textContent=`Admin fee: ${peso(gb?.admin_fee)}. Submit payment proof for approval.`;btn.textContent='PAY ADMIN FEE';btn.disabled=false;btn.onclick=feeAction;return}if(feePayment.status==='PAID'){state.innerHTML='Admin fee <span class="pepFeeStatus paid">APPROVED</span>. Email verification is required before ordering.';btn.textContent=verifiedEmail?'READY TO ORDER':'VERIFY EMAIL';btn.disabled=false;btn.onclick=verifiedEmail?()=>info('Ready to Order','Your admin fee is approved and your email is verified. You can continue ordering.'):openVerify;return}if(feePayment.status==='REJECTED'){state.innerHTML='Previous payment <span class="pepFeeStatus rejected">REJECTED</span>. You may submit a new payment proof.';btn.textContent='SUBMIT AGAIN';btn.disabled=false;btn.onclick=feeAction;return}state.innerHTML='Admin fee <span class="pepFeeStatus pending">PENDING APPROVAL</span>. Please wait for admin approval.';btn.textContent='VIEW PAYMENT';btn.disabled=false;btn.onclick=feeAction}
  function feeAction(){if(!gb)return info('No Open Group Buy','There is no open Group Buy right now.');if(feePayment?.status==='PAID'){if(verifiedEmail)info('Ready to Order','Your admin fee is approved and your email is verified. You can continue ordering.');else openVerify();return}if(feePayment?.status==='SUBMITTED'){info('Payment Pending','Your admin fee payment is waiting for admin approval. You will be able to verify your email after approval.');return}$('pepFeeGb').innerHTML=`<b>${esc(gb.customer_facing_name||gb.gb_number)}</b><br>Admin Fee: <b>${peso(gb.admin_fee)}</b>`;$('pepFeeName').value=feePayment?.full_name||localStorage.getItem('pepmosa_customer_name')||'';$('pepFeeTelegram').value=feePayment?.telegram_name||localStorage.getItem('pepmosa_telegram')||'';$('pepFeePhone').value=feePayment?.phone||localStorage.getItem('pepmosa_phone')||'';$('pepFeeProof').value='';$('pepFeeMsg').innerHTML='';$('pepFeeModal').classList.add('open')}
  async function submitFee(){const name=$('pepFeeName').value.trim(),tg=$('pepFeeTelegram').value.trim(),phone=$('pepFeePhone').value.trim(),file=$('pepFeeProof').files[0],msg=$('pepFeeMsg');if(!name||!tg||!phone||!file){msg.innerHTML='<div class="pepFeeNotice error">Please complete Full Name, Telegram Name, Mobile Number, and Payment Proof.</div>';return}if(file.size>5*1024*1024){msg.innerHTML='<div class="pepFeeNotice error">Payment proof must be 5MB or smaller.</div>';return}const S=sb();if(!S){msg.innerHTML='<div class="pepFeeNotice error">System is still loading. Please refresh.</div>';return}$('pepFeeSubmit').disabled=true;$('pepFeeSubmit').textContent='SUBMITTING…';try{const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${gb.gb_number}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await S.storage.from('payment-proofs').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;const url=S.storage.from('payment-proofs').getPublicUrl(path).data.publicUrl;const row={gb_number:gb.gb_number,email:null,full_name:name,telegram_name:tg,phone,payment_proof_url:url,amount:Number(gb.admin_fee||0),payment_reference:'PROOF UPLOAD',note:'Customer submitted payment proof',status:'SUBMITTED'};const ins=await S.from('admin_fee_payments').insert(row).select('*').single();if(ins.error)throw ins.error;feePayment=ins.data;localStorage.setItem('pepmosa_fee_payment_id',feePayment.id);localStorage.setItem('pepmosa_customer_name',name);localStorage.setItem('pepmosa_telegram',tg);localStorage.setItem('pepmosa_phone',phone);$('pepFeeModal').classList.remove('open');info('Payment Submitted ✓','Your admin fee payment proof has been submitted. Please wait for admin approval. You will be able to verify your email after approval.');await refreshFeeState()}catch(e){console.error(e);msg.innerHTML='<div class="pepFeeNotice error">Unable to submit payment proof. Please run admin-fee-customer-proof-migration.sql in Supabase SQL Editor if you have not done so.</div>'}finally{$('pepFeeSubmit').disabled=false;$('pepFeeSubmit').textContent='I HAVE PAID'}}
  function openVerify(){if(!feePayment||feePayment.status!=='PAID')return info('Approval Required','Your admin fee must be approved by admin before email verification.');$('pepVerifyEmail').value=localStorage.getItem('pepmosa_customer_email')||'';$('pepVerifyMsg').innerHTML='';$('pepVerifyModal').classList.add('open')}
  async function sendVerify(){const email=$('pepVerifyEmail').value.trim().toLowerCase(),msg=$('pepVerifyMsg');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){msg.innerHTML='<div class="pepFeeNotice error">Please enter a valid email.</div>';return}if(!feePayment||feePayment.status!=='PAID'){msg.innerHTML='<div class="pepFeeNotice error">Admin fee approval is still required.</div>';return}localStorage.setItem('pepmosa_customer_email',email);localStorage.setItem('pepmosa_pending_verify_email',email);const r=await sb().auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href,shouldCreateUser:true}});if(r.error){msg.innerHTML='<div class="pepFeeNotice error">'+esc(r.error.message)+'</div>';return}msg.innerHTML='<div class="pepFeeNotice success">Verification email sent. Open your inbox, click the verification link, then return to this page.</div>'}
  async function authReturn(){const pending=localStorage.getItem('pepmosa_pending_verify_email');if(!pending||!sb())return;const {data}=await sb().auth.getSession();if(data?.session?.user?.email?.toLowerCase()===pending.toLowerCase()){verifiedEmail=pending.toLowerCase();localStorage.setItem('pepmosa_verified_email',verifiedEmail);localStorage.removeItem('pepmosa_pending_verify_email');const paymentId=localStorage.getItem('pepmosa_fee_payment_id');if(paymentId)await sb().rpc('claim_admin_fee_payment',{p_payment_id:paymentId,p_email:verifiedEmail}).catch(()=>{});$('pepVerifyModal')?.classList.remove('open');info('Email Verified ✓','Your email has been verified. You can now add products to your cart and place an order.');await refreshFeeState();renderProducts()}}
  function minFor(v){const x=minimums.find(m=>m.variant_id===v);return Math.max(1,Number(x?.minimum_qty||1))}
  function renderProducts(){const grid=$('productGrid');if(!grid)return;const q=($('search')?.value||'').toLowerCase();const list=products.filter(p=>`${p.product_name} ${p.category} ${(p.product_variants||[]).map(v=>v.strength).join(' ')}`.toLowerCase().includes(q));if(!list.length){grid.innerHTML='<div class="card"><b>No products available yet.</b><br><span class="muted">No active products are available for this Group Buy.</span></div>';return}grid.innerHTML=list.map(p=>`<div class="card"><div class="productImg" style="height:180px">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.product_name)}">`:''}</div><h3>${esc(p.product_name)}</h3><div class="muted">${esc(p.description||'')}</div>${(p.product_variants||[]).map(v=>{const m=minFor(v.variant_id);return `<div class="pepVariantRow" style="display:flex;justify-content:space-between;gap:10px;align-items:center;border-top:1px dashed #ead9e5;padding:10px 0"><div><b>${esc(v.strength)}</b><br><span class="muted">${peso(v.price)} • minimum ${m}</span></div><input id="pepQty_${esc(v.variant_id)}" type="number" min="${m}" value="${m}" style="width:70px;padding:8px;border:1px solid #e5d4e0;border-radius:9px"><button class="pepFeeBtn" onclick="window.pepAddToCart('${esc(p.product_id)}','${esc(v.variant_id)}')">ADD</button></div>`}).join('')}</div>`).join('')}
  window.pepAddToCart=function(pid,vid){if(!feePayment||feePayment.status!=='PAID')return feeAction();if(!verifiedEmail)return openVerify();const p=products.find(x=>x.product_id===pid),v=p?.product_variants?.find(x=>x.variant_id===vid);if(!p||!v)return;const min=minFor(vid),q=Math.max(min,Number($('pepQty_'+vid)?.value||min));let cart=JSON.parse(localStorage.pepmosaCart||'[]');const old=cart.find(x=>x.variant_id===vid&&x.gb_number===gb.gb_number);if(old)old.qty+=q;else cart.push({gb_number:gb.gb_number,product_id:pid,variant_id:vid,product_name:p.product_name,strength:v.strength,unit_price:Number(v.price),qty:q});localStorage.pepmosaCart=JSON.stringify(cart);if(typeof window.renderCart==='function')window.renderCart();if($('cartCount'))$('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);info('Added to Cart',`${q} × ${p.product_name} ${v.strength} added to your cart.`)};
  function hookCheckout(){if(typeof window.checkout!=='function'||window.checkout.__pepGuard)return;const original=window.checkout;window.checkout=async function(){if(!feePayment||feePayment.status!=='PAID')return feeAction();if(!verifiedEmail)return openVerify();return original()};window.checkout.__pepGuard=true}
  function hookPlaceOrder(){if(typeof window.placeOrder!=='function'||window.placeOrder.__pepGuard)return;const original=window.placeOrder;window.placeOrder=async function(){if(!feePayment||feePayment.status!=='PAID')return feeAction();if(!verifiedEmail)return openVerify();if($('email'))$('email').value=verifiedEmail;return original()};window.placeOrder.__pepGuard=true}
  async function feeWatch(){if(!gb||!feePayment||feePayment.status!=='SUBMITTED')return;await refreshFeeState()}
  async function load(){try{const S=sb();if(!S)return;ensureUI();const r=await S.from('group_buys').select('*').eq('status','OPEN').order('created_at',{ascending:false}).limit(1).maybeSingle();if(r.error)throw r.error;gb=r.data;if(!gb){if($('gbStatus'))$('gbStatus').innerHTML='<div class="notice error">No open Group Buy right now.</div>';return}if($('gbStatus'))$('gbStatus').innerHTML=`<b>${esc(gb.customer_facing_name||gb.gb_number)}</b> <span class="status open">OPEN</span>`;const links=await S.from('gb_categories').select('category_name').eq('gb_number',gb.gb_number);const allowed=new Set((links.data||[]).map(x=>x.category_name));const ps=await S.from('products').select('product_id,product_name,category,description,image_url,active,product_variants(variant_id,strength,price,active)').eq('active',true);if(ps.error)throw ps.error;products=(allowed.size?ps.data.filter(p=>allowed.has(p.category)):ps.data).map(p=>({...p,product_variants:(p.product_variants||[]).filter(v=>v.active!==false)}));const ms=await S.from('gb_minimum_quantities').select('gb_number,product_id,variant_id,minimum_qty').eq('gb_number',gb.gb_number);minimums=ms.data||[];renderProducts();feePayment=await findFee();await refreshFeeState();hookCheckout();hookPlaceOrder();authReturn();setInterval(()=>feeWatch().catch(()=>{}),10000)}catch(e){console.error('PEPMOSA storefront:',e);if($('gbStatus'))$('gbStatus').innerHTML='<div class="notice error">Unable to load the current Group Buy. Please refresh and try again.</div>'}}
  function boot(){ensureUI();let n=0;const t=setInterval(()=>{if(sb()){clearInterval(t);load()}if(++n>100)clearInterval(t)},100);if(sb())load()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
